---
# Compose file which enables emulation out of the box for non-AArch64 systems.
#
# Comes out with sane defaults, feel free to configure as needed.

version: "3"

services:
  build-nixos:
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - HOME=/home/nixos
      - USER=nixos
