---
# Compose file which provides automagic building of NixOS SD images for AArch64 systems.
# Use together with `docker-compose.emulation.yml` if a transparent emulation layer is required.

# Comes out with sane defaults, feel free to configure as needed.
# NOTE: the configuration used to build NixOS resides in the parent directory as `sd-image.nix`

version: "3"

services:
  # Main container, requires no elevated privileges to run. Builds NixOS.
  build-nixos:
    image: ghcr.io/ramblurr/ovos-rpi-nixos-builder:latest
    # Or use these settings
    #build:
    #  context: build-nixos
    #  args:
    #    IMAGE_BASE: $IMAGE_BASE
    #    NIXPKGS_URL: "https://github.com/nixos/nixpkgs"
    #    NIXPKGS_BRANCH: "release-23.05"
    working_dir: /home/nixos
    # Main command line, left here so it can be changed easily. The container will:
    volumes:
      - ..:/build
