name: Builder

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/Builder.yaml"
      - "docker/**"

jobs:
  build-builder:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Setup GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/ramblurr/ovos-rpi-nixos-builder:latest
          file: docker/build-nixos/Dockerfile
          context: docker/build-nixos
          build-args: |-
            IMAGE_BASE=arm64v8/
            NIXPKGS_URL=https://github.com/nixos/nixpkgs
            NIXPKGS_BRANCH=release-23.05
          cache-from: type=gha
          cache-to: type=gha,mode=max
