name: nix-build-on-demand-docker
on:
  push:
    branches:
      - main
    paths:
      - '**/*.nix'

jobs:
  build-dev-image:
    name: Build dev image
    runs-on: ubuntu-22.04
    environment:
      name: dev
    steps:
    - uses: actions/checkout@v3.5.3
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-23.05
        extra_nix_config: |
          extra-platforms = aarch64-linux
    - name: Check nix.conf
      run: cat /etc/nix/nix.conf
    - name: Register binfmt
      run: |
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - name: Test binfmt availability
      run: |
        cat /proc/sys/fs/binfmt_misc/qemu-aarch64
    - name: Build SD Image
      run: |
        nix-build '<nixpkgs/nixos>'  \
          -A config.system.build.sdImage \
          -I nixos-config=./configuration.dev.sdImage.nix \
          --argstr system aarch64-linux \
          --option sandbox false
    - uses: actions/upload-artifact@v3
      with:
        name: sd-image.img
        path: ./result/sd-image/*.img*
